/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tienda_automoviles.gui;

import com.mycompany.tienda_automoviles.logica.Automovil;
import com.mycompany.tienda_automoviles.logica.ControladoraLogica;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.eclipse.persistence.internal.sessions.DirectCollectionChangeRecord.NULL;

/**
 *
 * @author Gary
 */
public class PantallaVerAutos extends javax.swing.JFrame {

    ControladoraLogica control = null;
    /**
     * Creates new form PantallaVerAutos
     */
    public PantallaVerAutos() {
        control = new ControladoraLogica();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGUI = new javax.swing.JTable();
        eliminarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setText("<-");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tablaGUI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaGUI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaGUI);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 941, 664));

        eliminarBtn.setText("X");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 107, 110, -1));

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 169, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        Pantalla_Principal pantalla = new Pantalla_Principal();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        if (tablaGUI.getRowCount() > 0) {
            if (tablaGUI.getSelectedRow() != -1) {
                int id = (int) tablaGUI.getValueAt(tablaGUI.getSelectedRow(), 0);
                control.eliminarAutomovil(id);

                JOptionPane.showMessageDialog(null, "Vehiculo eliminado con exito");
                

            }else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione la ID de un vehiculo");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione la ID un vehiculo");
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        if (tablaGUI.getRowCount() > 0) {
            if (tablaGUI.getSelectedRow() != -1) {
                int id = (int) tablaGUI.getValueAt(tablaGUI.getSelectedRow(), 0);
                
                PantallaEditarDatos pantalla = new PantallaEditarDatos(id);
                pantalla.setVisible(true);
                pantalla.setLocationRelativeTo(null);

                this.setVisible(false);

            }else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione la ID de un vehiculo");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione la ID un vehiculo");
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGUI;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        //Que la tabla no sea editable
        DefaultTableModel tabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        //Nombre de Columnas
        String titulos[] = {"ID", "MARCA", "MODELO", "COLOR", "PATENTE"};
        tabla.setColumnIdentifiers(titulos);
        
        if (control.buscarTodosAutomoviles()!=null) {
            for (Automovil auto : control.buscarTodosAutomoviles()) {
                Object[] objeto = {auto.getId(), auto.getMarca(), auto.getModelo(), auto.getColor(), auto.getPatente()};

                tabla.addRow(objeto);
            }
            tablaGUI.setModel(tabla);
            //Recargar tablaGUI
            
        }
    }
}
